/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.almacen.mx.view.aplicaciondepartamentomantenimiento;

import com.almacen.mx.view.aplicaciondepartamentomantenimiento.customUI.CustomHeader;
import javax.swing.table.JTableHeader;

/**
 *
 * @author acost
 */
public class AreasTabla extends javax.swing.JPanel {

    /**
     * Creates new form AreasTabla
     */
    public AreasTabla() {
        initComponents();
        manualInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panel.setBackground(new java.awt.Color(44, 60, 67));
        panel.setLayout(new java.awt.BorderLayout(30, 30));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll.setViewportView(tabla);

        panel.add(scroll, java.awt.BorderLayout.CENTER);
        panel.add(jLabel1, java.awt.BorderLayout.LINE_END);
        panel.add(jLabel2, java.awt.BorderLayout.PAGE_START);
        panel.add(jLabel3, java.awt.BorderLayout.LINE_START);
        panel.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        add(panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    //<editor-fold defaultstate="collapsed" desc="Metodos usados para la interfaz">
    private void manualInitComponents() {
        JTableHeader headerEntradas = tabla.getTableHeader();
        headerEntradas.setDefaultRenderer(new CustomHeader());
        tabla.setTableHeader(headerEntradas);
    }
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
