/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.almacen.mx.view.aplicaciondepartamentomantenimiento;

import java.awt.Insets;
import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author acost
 */
public class AreasMenu extends javax.swing.JPanel {

    /**
     * Creates new form AreasMenu
     */
    public AreasMenu() {
        initComponents();
        manualInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        botones = new javax.swing.JPanel();
        tablaButton = new javax.swing.JButton();
        formularioButton = new javax.swing.JButton();
        ventanas = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        panelMenu.setBackground(new java.awt.Color(44, 60, 67));
        panelMenu.setLayout(new java.awt.BorderLayout());

        botones.setBackground(new java.awt.Color(44, 60, 67));
        botones.setPreferredSize(new java.awt.Dimension(911, 130));

        tablaButton.setText("TABLA");
        tablaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaButtonMouseClicked(evt);
            }
        });

        formularioButton.setText("FORMULARIO");
        formularioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formularioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonesLayout = new javax.swing.GroupLayout(botones);
        botones.setLayout(botonesLayout);
        botonesLayout.setHorizontalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonesLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(tablaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addGap(86, 86, 86)
                .addComponent(formularioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(249, 249, 249))
        );
        botonesLayout.setVerticalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonesLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tablaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formularioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        panelMenu.add(botones, java.awt.BorderLayout.PAGE_END);
        panelMenu.add(ventanas, java.awt.BorderLayout.CENTER);

        add(panelMenu, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaButtonMouseClicked
        ventanas.setSelectedIndex(0);
    }//GEN-LAST:event_tablaButtonMouseClicked

    private void formularioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formularioButtonMouseClicked
        ventanas.setSelectedIndex(1);
    }//GEN-LAST:event_formularioButtonMouseClicked

    private void manualInitComponents(){
        ventanas.add(at);
        ventanas.add(afm);
        
        ventanas.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0;

            }
             @Override
            protected void installDefaults() {
                super.installDefaults();
                tabAreaInsets = new Insets(0, 0, 0, 0);
                contentBorderInsets = new Insets(0, 0, 0, 0);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botones;
    private javax.swing.JButton formularioButton;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JButton tablaButton;
    private javax.swing.JTabbedPane ventanas;
    // End of variables declaration//GEN-END:variables
    AreasFormularioMenu afm = new AreasFormularioMenu();
    AreasTabla at = new AreasTabla();
}
