/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.almacen.mx.view.aplicaciondepartamentomantenimiento;

import com.almacen.mx.view.aplicaciondepartamentomantenimiento.customUI.CustomHeader;
import javax.swing.table.JTableHeader;

/**
 *
 * @author acost
 */
public class RequisicionesTabla extends javax.swing.JPanel {

    /**
     * Creates new form RequisicionesTabla
     */
    public RequisicionesTabla() {
        initComponents();
        manualInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEntrada = new javax.swing.JPanel();
        scrollEntradas = new javax.swing.JScrollPane();
        tablaEntradas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelEntrada.setBackground(new java.awt.Color(44, 60, 67));
        panelEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEntradaMouseClicked(evt);
            }
        });
        panelEntrada.setLayout(new java.awt.BorderLayout(30, 30));

        scrollEntradas.setBackground(new java.awt.Color(40, 60, 67));

        tablaEntradas.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Piezas", "Codigo", "Nombre", "Estado", "Proveedor", "Fecha"
            }
        ));
        tablaEntradas.setGridColor(new java.awt.Color(40, 60, 67));
        tablaEntradas.setRowHeight(30);
        tablaEntradas.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tablaEntradas.getTableHeader().setResizingAllowed(false);
        tablaEntradas.getTableHeader().setReorderingAllowed(false);
        scrollEntradas.setViewportView(tablaEntradas);

        panelEntrada.add(scrollEntradas, java.awt.BorderLayout.CENTER);
        panelEntrada.add(jLabel1, java.awt.BorderLayout.PAGE_START);
        panelEntrada.add(jLabel2, java.awt.BorderLayout.LINE_START);
        panelEntrada.add(jLabel3, java.awt.BorderLayout.LINE_END);
        panelEntrada.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        add(panelEntrada, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void panelEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntradaMouseClicked
        tablaEntradas.clearSelection();
    }//GEN-LAST:event_panelEntradaMouseClicked
    
    private void manualInitComponents() {
        JTableHeader headerEntradas = tablaEntradas.getTableHeader();
        headerEntradas.setDefaultRenderer(new CustomHeader());
        tablaEntradas.setTableHeader(headerEntradas);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelEntrada;
    private javax.swing.JScrollPane scrollEntradas;
    private javax.swing.JTable tablaEntradas;
    // End of variables declaration//GEN-END:variables
}
