/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.almacen.mx.view.aplicaciondepartamentomantenimiento;

import aplicaciondepartamentomantenimiento.customUI.ScrollBarCustom;

/**
 *
 * @author acost
 */
public class RequisicionesFormularioMenu extends javax.swing.JPanel {

    /**
     * Creates new form RequisicionesFormularioMenu
     */
    public RequisicionesFormularioMenu() {
        initComponents();
        manualInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        scrollPanelPrincipal = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        direccionRadioButton = new javax.swing.JRadioButton();
        jefaturaRadioButton = new javax.swing.JRadioButton();
        planeacionRadioButton = new javax.swing.JRadioButton();
        comprasRadioButton = new javax.swing.JRadioButton();
        subdireccionRadioButton = new javax.swing.JRadioButton();
        recRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        observacionesTextPane = new javax.swing.JTextPane();
        limpiarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        idErrorLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        scrollPanelPrincipal.setBackground(new java.awt.Color(0, 102, 102));

        panelPrincipal.setBackground(new java.awt.Color(0, 102, 102));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(850, 450));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID REQUISICIONES");

        idTextField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        direccionRadioButton.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        direccionRadioButton.setText("SUBDIRECCION");

        jefaturaRadioButton.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jefaturaRadioButton.setText("JEFATURA");
        jefaturaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jefaturaRadioButtonActionPerformed(evt);
            }
        });

        planeacionRadioButton.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        planeacionRadioButton.setText("PLANEACION");

        comprasRadioButton.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        comprasRadioButton.setText("COMPRAS");

        subdireccionRadioButton.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        subdireccionRadioButton.setText("DIRECCION");

        recRadioButton.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        recRadioButton.setText("REC");

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OBSERVACIONES");

        scrollPane.setViewportView(observacionesTextPane);

        limpiarButton.setBackground(new java.awt.Color(255, 51, 51));
        limpiarButton.setText("LIMPIAR");
        limpiarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarButtonMouseClicked(evt);
            }
        });

        guardarButton.setBackground(new java.awt.Color(0, 153, 51));
        guardarButton.setText("GUARDAR");
        guardarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarButtonMouseClicked(evt);
            }
        });

        idErrorLabel.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        idErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        idErrorLabel.setText("ERROR");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(direccionRadioButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(289, 289, 289))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(idErrorLabel))
                        .addGap(166, 166, 166)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subdireccionRadioButton)
                            .addComponent(comprasRadioButton)
                            .addComponent(planeacionRadioButton)
                            .addComponent(jefaturaRadioButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(recRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpiarButton)
                        .addGap(34, 34, 34)
                        .addComponent(guardarButton)
                        .addGap(59, 59, 59))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idErrorLabel)
                        .addGap(16, 16, 16)
                        .addComponent(jefaturaRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(planeacionRadioButton))
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(direccionRadioButton)
                .addGap(26, 26, 26)
                .addComponent(subdireccionRadioButton)
                .addGap(28, 28, 28)
                .addComponent(comprasRadioButton)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(recRadioButton))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limpiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        scrollPanelPrincipal.setViewportView(panelPrincipal);

        add(scrollPanelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    //<editor-fold defaultstate="collapsed" desc="Metodos para la interfaz">
    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void jefaturaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jefaturaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jefaturaRadioButtonActionPerformed

    private void limpiarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarButtonMouseClicked
        limpiar();
    }//GEN-LAST:event_limpiarButtonMouseClicked

    private void guardarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtonMouseClicked
        comprobarDatos();   
    }//GEN-LAST:event_guardarButtonMouseClicked
    
    private void manualInitComponents(){
        scrollPanelPrincipal.setVerticalScrollBar(new ScrollBarCustom());
        scrollPanelPrincipal.getVerticalScrollBar().setUnitIncrement(15);
        
        grupo.add(jefaturaRadioButton);
        grupo.add(planeacionRadioButton);
        grupo.add(subdireccionRadioButton);
        grupo.add(direccionRadioButton);
        grupo.add(comprasRadioButton);
        grupo.add(recRadioButton);
        
        ocultarErrores();
    }
    
    private void ocultarErrores(){
        idErrorLabel.setText("");
    }
    
    private void limpiar(){
        idTextField.setText("");
        observacionesTextPane.setText("");
        ocultarErrores();
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Metodos para la obtencion de datos">
    //ESTE METODO COMPROBARA QUE CADA DATO EN LOS ELEMENTOS PARA RELLENAR SEA DEL FORMATO APROPIADO Y QUE NO ESTE VACIO 
    //SI TODOS LOS DATOS ESTAN CORRECTOS, DEVUELVE TRUE, DE LO CONTRARIO DEVUELVE UN FALSE
    //CUANDO UN FORMATO NO ESTE CORRECTO, SE INDICARA CON UN MENSAJE JUSTO DEBAJO DEL ELEMENTO EL CUAL GENERE EL ERROR
     private boolean comprobarDatos() {
         ocultarErrores();
         //COMPROBAR QUE EL TEXTO ESCRITO EN ID TEXTFIELD SEAN SOLO NUMEROS
         boolean error = false;
        try {
            Integer.valueOf(idTextField.getText());           
        } catch (NumberFormatException e) {
            idErrorLabel.setText("Error");
            error = true;
        }
        
         //SI HUBO ALGUN ERROR EL METODO REGRESA FALSE
        if(error){
            return false;
        }
        
        //SI NO HUBO NINGUN ERROR EL METODO REGRESA TRUE
        ocultarErrores();
        return true;
     }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton comprasRadioButton;
    private javax.swing.JRadioButton direccionRadioButton;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel idErrorLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jefaturaRadioButton;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JTextPane observacionesTextPane;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton planeacionRadioButton;
    private javax.swing.JRadioButton recRadioButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPanelPrincipal;
    private javax.swing.JRadioButton subdireccionRadioButton;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
