/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.almacen.mx.view.aplicaciondepartamentomantenimiento;

import com.almacen.mx.bo.SalidaBO;
import com.almacen.mx.db.Conexion;
import com.almacen.mx.view.aplicaciondepartamentomantenimiento.customUI.CustomHeader;
import com.almacen.mx.view.aplicaciondepartamentomantenimiento.customUI.ModeloTabla;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author acost
 */
public class SalidasMenu extends javax.swing.JPanel {

    /**
     * Creates new form SalidasMenu
     */
    public SalidasMenu() {
        initComponents();
        manualInitComponents();
        SalidaBO sabo = new SalidaBO();
        
        sabo.listarSalidaID(tablaSalida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSalida = new javax.swing.JPanel();
        scrollSalida = new javax.swing.JScrollPane();
        tablaSalida = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelSalida.setBackground(new java.awt.Color(44, 60, 67));
        panelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSalidaMouseClicked(evt);
            }
        });
        panelSalida.setLayout(new java.awt.BorderLayout(30, 30));

        tablaSalida.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSalida.setRowHeight(30);
        tablaSalida.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tablaSalida.getTableHeader().setResizingAllowed(false);
        tablaSalida.getTableHeader().setReorderingAllowed(false);
        scrollSalida.setViewportView(tablaSalida);

        panelSalida.add(scrollSalida, java.awt.BorderLayout.CENTER);
        panelSalida.add(jLabel1, java.awt.BorderLayout.PAGE_START);
        panelSalida.add(jLabel2, java.awt.BorderLayout.LINE_END);
        panelSalida.add(jLabel3, java.awt.BorderLayout.LINE_START);
        panelSalida.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        add(panelSalida, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Metodos usados para la interfaz">
    private void panelSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalidaMouseClicked
        tablaSalida.clearSelection();
    }//GEN-LAST:event_panelSalidaMouseClicked

    private void manualInitComponents(){
        JTableHeader headerSalidas = tablaSalida.getTableHeader();
	headerSalidas.setDefaultRenderer(new CustomHeader());
	tablaSalida.setTableHeader(headerSalidas);
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelSalida;
    private javax.swing.JScrollPane scrollSalida;
    private javax.swing.JTable tablaSalida;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel modeloTablaSalida;
    //</editor-fold>
}
