/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.almacen.mx.view.aplicaciondepartamentomantenimiento;

import aplicaciondepartamentomantenimiento.customUI.ScrollBarCustom;
import static com.almacen.mx.view.aplicaciondepartamentomantenimiento.StockMenu.ventanas;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author acost
 */
public class SalidasStockMenu extends javax.swing.JPanel {

    /**
     * Creates new form SalidasStockMenu
     */
    public SalidasStockMenu() {
        initComponents();
        manaulInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanePrincipal = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        destinoComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        piezasTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        limpiarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();
        observacionesTextPane = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        codigoErrorLabel = new javax.swing.JLabel();
        destinoErrorLabel = new javax.swing.JLabel();
        piezasErrorLabel = new javax.swing.JLabel();
        fechaErrorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 60, 67));
        setLayout(new java.awt.BorderLayout());

        scrollPanePrincipal.setBackground(new java.awt.Color(0, 102, 102));
        scrollPanePrincipal.setPreferredSize(new java.awt.Dimension(1035, 560));

        panelPrincipal.setBackground(new java.awt.Color(0, 102, 102));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(440, 520));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DESTINO:");

        codigoTextField.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CODIGO PRODUCTO:");

        destinoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PIEZAS:");

        piezasTextField.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FECHA:");

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("OBSERVACIONES:");

        limpiarButton.setBackground(new java.awt.Color(255, 51, 51));
        limpiarButton.setText("LIMPIAR");
        limpiarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarButtonMouseClicked(evt);
            }
        });

        guardarButton.setBackground(new java.awt.Color(0, 153, 51));
        guardarButton.setText("GUARDAR");
        guardarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarButtonMouseClicked(evt);
            }
        });

        volverButton.setBackground(new java.awt.Color(102, 102, 102));
        volverButton.setText("VOLVER");
        volverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverButtonMouseClicked(evt);
            }
        });

        jTextPane1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        observacionesTextPane.setViewportView(jTextPane1);

        codigoErrorLabel.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        codigoErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        codigoErrorLabel.setText("ERROR");

        destinoErrorLabel.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        destinoErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        destinoErrorLabel.setText("ERROR");

        piezasErrorLabel.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        piezasErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        piezasErrorLabel.setText("ERROR");

        fechaErrorLabel.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        fechaErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        fechaErrorLabel.setText("ERROR");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(destinoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codigoTextField)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(piezasTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigoErrorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(piezasErrorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(261, 261, 261))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(destinoErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(443, 443, 443)))
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(observacionesTextPane))
                                .addGap(243, 243, 243))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(fechaErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(volverButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpiarButton)
                        .addGap(18, 18, 18)
                        .addComponent(guardarButton)
                        .addGap(233, 233, 233))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoErrorLabel)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(observacionesTextPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinoErrorLabel)
                .addGap(58, 58, 58)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piezasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaErrorLabel)
                    .addComponent(piezasErrorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        scrollPanePrincipal.setViewportView(panelPrincipal);

        add(scrollPanePrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    //<editor-fold defaultstate="collapsed" desc="Metodos Interfaz">
    private void volverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMouseClicked
        StockMenu.volverStock();
    }//GEN-LAST:event_volverButtonMouseClicked

    private void guardarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtonMouseClicked
        comprobarDatos();
    }//GEN-LAST:event_guardarButtonMouseClicked

    private void limpiarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarButtonMouseClicked
        limpiar();
    }//GEN-LAST:event_limpiarButtonMouseClicked
    
    private void manaulInit(){
        scrollPanePrincipal.setVerticalScrollBar(new ScrollBarCustom());
        scrollPanePrincipal.getVerticalScrollBar().setUnitIncrement(30);
        scrollPanePrincipal.setHorizontalScrollBar(new ScrollBarCustom());
        scrollPanePrincipal.getHorizontalScrollBar().setUnitIncrement(5);
        dateChooser.setDate(date);
        
        cambiarFormatoFecha();
        
        ocultarErrores();
    }
    
    private void ocultarErrores(){
        codigoErrorLabel.setText("");
        destinoErrorLabel.setText("");
        piezasErrorLabel.setText("");
        fechaErrorLabel.setText("");
    }
    
    private void limpiar(){
        codigoTextField.setText("");
        destinoComboBox.setSelectedIndex(0);
        piezasTextField.setText("");
        dateChooser.setDate(date);
        ocultarErrores();
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Metodos para obtener datos">
    
    private void cambiarFormatoFecha(){
        // EL STRING QUE RECIBE ESTE METODO ES EL FORMATO EN EL QUE SE MUESTRA LA FECHA DE HAY EN EL DISPLAY DE FECHA
        // ESTE FORMATO OBEDECE EL FORMATO DE CUALQUEIR DATEFORMAT, ASI QUE SI SE DESEA CAMBIAR PARA ADAPTARLO PARA EL 
        // FORMATO QUE ACCEPTE LA BASE DE DATOS SE DEBERA CONSIDERAR ESE FORMATO
        formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
        dateChooser.setDateFormatString("dd-MM-yyyy");
    }
    
    //ESTE METODO COMPROBARA QUE CADA DATO EN LOS ELEMENTOS PARA RELLENAR SEA DEL FORMATO APROPIADO Y QUE NO ESTE VACIO 
    //SI TODOS LOS DATOS ESTAN CORRECTOS, DEVUELVE TRUE, DE LO CONTRARIO DEVUELVE UN FALSE
    //CUANDO UN FORMATO NO ESTE CORRECTO, SE INDICARA CON UN MENSAJE JUSTO DEBAJO DEL ELEMENTO EL CUAL GENERE EL ERROR
    private boolean comprobarDatos(){       
        
        //ESTA VARIABLE VALIDARA SI HUBO UN ERROR DURANTE LAS COMPROBACIONES, SI LO HAY ESTE VALOR SERA TRUE
        boolean error = false;
        
        //COMPROBAR QUE EL TEXTO ESCRITO EN CODIGO TEXTFIELD SEAN SOLO NUMEROS
        try{
            Integer.valueOf(codigoTextField.getText());
            codigoErrorLabel.setText("");
        }catch(NumberFormatException e){
            codigoErrorLabel.setText("Error");   
            error = true;
        }
        
        //COMPROBAR QUE EL ELEMENTO SELECCIONADO EN DESTINO COMBOBOX NO SEA EL PRIMER ELEMENTO
        //ESTO ESTA TOMANDO EN CUENTA QUE SIEMPRE EL PRIMER ELEMENTO DEL COMBOBOX ESTARA VACIA
        if(destinoComboBox.getSelectedIndex() == 0){
            destinoErrorLabel.setText("Error");
            error = true;
        } else{
            destinoErrorLabel.setText("");
        }
        
        //COMPROBAR QUE EL TEXTO ESCRITO EN PIEZAS TEXTFIELD SEAN SOLO NUMEROS
        try{
            Integer.valueOf(piezasTextField.getText());
            piezasErrorLabel.setText("");
        }catch(NumberFormatException e){
            piezasErrorLabel.setText("Error");   
            error = true;
        }
        
        //COMPROBAR QUE EL FORMATO ESCRITO EN DATECHOOSER SEA IGUAL AL DEL "formatoFecha"
        try {
            Date fechaE = null;
            System.out.println(formatoFecha.format(dateChooser.getDate()));
            fechaE = formatoFecha.parse(formatoFecha.format(dateChooser.getDate()));
            fechaErrorLabel.setText("");
        } catch (Exception ex) {
            fechaErrorLabel.setText("Error");
            error = true;
        }
        
        //SI HUBO ALGUN ERROR EL METODO REGRESA FALSE
        if(error){
            return false;
        }
        
        //SI NO HUBO NINGUN ERROR EL METODO REGRESA TRUE
        ocultarErrores();
        return true;
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoErrorLabel;
    private javax.swing.JTextField codigoTextField;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JComboBox<String> destinoComboBox;
    private javax.swing.JLabel destinoErrorLabel;
    private javax.swing.JLabel fechaErrorLabel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JScrollPane observacionesTextPane;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel piezasErrorLabel;
    private javax.swing.JTextField piezasTextField;
    private javax.swing.JScrollPane scrollPanePrincipal;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
    private SimpleDateFormat formatoFecha;
    Date date = new Date();
    //</editor-fold>
}
