/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.almacen.mx.view.aplicaciondepartamentomantenimiento;

import aplicaciondepartamentomantenimiento.customUI.CustomHeader;
import aplicaciondepartamentomantenimiento.customUI.ModeloTabla;
import aplicaciondepartamentomantenimiento.customUI.ScrollBarCustom;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import static java.lang.Integer.parseInt;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author acost
 */
public class StockMenu extends javax.swing.JPanel {

    /**
     * Creates new form StockMenu
     */
    public StockMenu() {
        initComponents();       
        manualInitComponents();
        ocultarErrores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStock = new javax.swing.JPanel();
        botones = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        entradas = new javax.swing.JPanel();
        meLabel = new javax.swing.JLabel();
        modificarEntradasButton = new javax.swing.JLabel();
        salidas = new javax.swing.JPanel();
        msLabel = new javax.swing.JLabel();
        modificarSalidasButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ventanas = new javax.swing.JPanel();
        modificarSalidasMenu = new javax.swing.JPanel();
        campos = new javax.swing.JPanel();
        sNumeroTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sPiezasTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        sCodigoTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sNombreTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        sPersonalTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        sLugarTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        sFechaTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        sFechaButton = new javax.swing.JButton();
        sGuardarButton = new javax.swing.JButton();
        sVolverButton = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sEstadoTextField = new javax.swing.JTextField();
        sNumeroErrorLabel = new javax.swing.JLabel();
        sPiezasErrorLabel = new javax.swing.JLabel();
        sCodigoErrorLabel = new javax.swing.JLabel();
        sNombreErrorLabel = new javax.swing.JLabel();
        sPersonalErrorLabel = new javax.swing.JLabel();
        sLugarErrorLabel = new javax.swing.JLabel();
        sEstadoErrorLabel = new javax.swing.JLabel();
        sFechaErrorLabel = new javax.swing.JLabel();
        modificarEntradasMenu = new javax.swing.JPanel();
        campos2 = new javax.swing.JPanel();
        eNumeroTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ePiezasTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eCodigoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        eNombreTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eEstadoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        eProveedorTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        eFechaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        eFechaButton = new javax.swing.JButton();
        eGuardarButton = new javax.swing.JButton();
        eVolverButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        eNumeroErrorLabel = new javax.swing.JLabel();
        ePiezasErrorLabel = new javax.swing.JLabel();
        eCodigoErrorLabel = new javax.swing.JLabel();
        eNombreErrorLabel = new javax.swing.JLabel();
        eEstadoErrorLabel = new javax.swing.JLabel();
        eProveedorErrorLabel = new javax.swing.JLabel();
        eFechaErrorLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tabla = new javax.swing.JPanel();
        scrollStock = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        panelStock.setBackground(new java.awt.Color(44, 60, 67));
        panelStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelStockMouseClicked(evt);
            }
        });
        panelStock.setLayout(new java.awt.BorderLayout());

        botones.setOpaque(false);
        botones.setPreferredSize(new java.awt.Dimension(510, 130));
        botones.setLayout(new java.awt.BorderLayout(300, 0));

        centro.setMaximumSize(new java.awt.Dimension(500, 130));
        centro.setOpaque(false);
        centro.setPreferredSize(new java.awt.Dimension(210, 130));
        centro.setLayout(new java.awt.BorderLayout());

        entradas.setOpaque(false);
        entradas.setPreferredSize(new java.awt.Dimension(110, 100));
        entradas.setLayout(new java.awt.BorderLayout());

        meLabel.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        meLabel.setForeground(new java.awt.Color(255, 255, 255));
        meLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meLabel.setText("<HTML><center>MODIFICAR <p> ENTRADAS");
        meLabel.setPreferredSize(new java.awt.Dimension(81, 30));
        entradas.add(meLabel, java.awt.BorderLayout.PAGE_START);

        modificarEntradasButton.setBackground(new java.awt.Color(0, 51, 51));
        modificarEntradasButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificarEntradasButton.setPreferredSize(new java.awt.Dimension(50, 50));
        modificarEntradasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarEntradasButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarEntradasButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarEntradasButtonMouseExited(evt);
            }
        });
        entradas.add(modificarEntradasButton, java.awt.BorderLayout.CENTER);

        centro.add(entradas, java.awt.BorderLayout.WEST);

        salidas.setOpaque(false);
        salidas.setPreferredSize(new java.awt.Dimension(110, 100));
        salidas.setLayout(new java.awt.BorderLayout());

        msLabel.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        msLabel.setForeground(new java.awt.Color(255, 255, 255));
        msLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msLabel.setText("<HTML><center>MODIFICAR <p> SALIDAS");
        msLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salidas.add(msLabel, java.awt.BorderLayout.PAGE_START);

        modificarSalidasButton.setBackground(new java.awt.Color(0, 51, 51));
        modificarSalidasButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificarSalidasButton.setPreferredSize(new java.awt.Dimension(50, 50));
        modificarSalidasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarSalidasButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarSalidasButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarSalidasButtonMouseExited(evt);
            }
        });
        salidas.add(modificarSalidasButton, java.awt.BorderLayout.CENTER);

        centro.add(salidas, java.awt.BorderLayout.EAST);

        botones.add(centro, java.awt.BorderLayout.CENTER);
        botones.add(jLabel1, java.awt.BorderLayout.WEST);
        botones.add(jLabel2, java.awt.BorderLayout.EAST);

        panelStock.add(botones, java.awt.BorderLayout.PAGE_END);

        ventanas.setOpaque(false);
        ventanas.setLayout(new java.awt.BorderLayout(30, 30));

        modificarSalidasMenu.setBackground(new java.awt.Color(204, 204, 204));
        modificarSalidasMenu.setLayout(new java.awt.BorderLayout());

        campos.setOpaque(false);

        sNumeroTextField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("NUMERO:");

        sPiezasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPiezasTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setText("PIEZAS:");

        jLabel21.setText("CODIGO:");

        jLabel22.setText("NOMBRE:");

        sPersonalTextField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setText("PERSONAL:");

        sLugarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sLugarTextFieldActionPerformed(evt);
            }
        });

        jLabel24.setText("LUGAR:");

        sFechaTextField.setText("DIA/MES/AÑO");
        sFechaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sFechaTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sFechaTextFieldMouseExited(evt);
            }
        });

        jLabel25.setText("FECHA:");

        sFechaButton.setText("HOY");
        sFechaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFechaButtonActionPerformed(evt);
            }
        });

        sGuardarButton.setBackground(new java.awt.Color(153, 255, 153));
        sGuardarButton.setText("GUARDAR");
        sGuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sGuardarButtonActionPerformed(evt);
            }
        });

        sVolverButton.setBackground(new java.awt.Color(255, 153, 153));
        sVolverButton.setText("VOLVER");
        sVolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sVolverButtonActionPerformed(evt);
            }
        });

        jLabel26.setText("REGISTRAR NUEVA SALIDA");

        jLabel11.setText("ESTADO:");

        sNumeroErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        sNumeroErrorLabel.setText("ERROR");

        sPiezasErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        sPiezasErrorLabel.setText("ERROR");

        sCodigoErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        sCodigoErrorLabel.setText("ERROR");

        sNombreErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        sNombreErrorLabel.setText("ERROR");

        sPersonalErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        sPersonalErrorLabel.setText("ERROR");

        sLugarErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        sLugarErrorLabel.setText("ERROR");

        sEstadoErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        sEstadoErrorLabel.setText("ERROR");

        sFechaErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        sFechaErrorLabel.setText("ERROR");

        javax.swing.GroupLayout camposLayout = new javax.swing.GroupLayout(campos);
        campos.setLayout(camposLayout);
        camposLayout.setHorizontalGroup(
            camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
            .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(camposLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(274, 274, 274)
                            .addComponent(jLabel26))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(sNumeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(218, 218, 218)
                            .addComponent(jLabel23)
                            .addGap(19, 19, 19)
                            .addComponent(sPersonalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(sNumeroErrorLabel)
                            .addGap(425, 425, 425)
                            .addComponent(sPersonalErrorLabel))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel20)
                            .addGap(11, 11, 11)
                            .addComponent(sPiezasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(242, 242, 242)
                            .addComponent(jLabel24)
                            .addGap(19, 19, 19)
                            .addComponent(sLugarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(sPiezasErrorLabel)
                            .addGap(425, 425, 425)
                            .addComponent(sLugarErrorLabel))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(sCodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(236, 236, 236)
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(sEstadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(sCodigoErrorLabel)
                            .addGap(425, 425, 425)
                            .addComponent(sEstadoErrorLabel))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel22)
                            .addGap(11, 11, 11)
                            .addComponent(sNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(251, 251, 251)
                            .addComponent(jLabel25)
                            .addGap(6, 6, 6)
                            .addComponent(sFechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(sFechaButton))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(sNombreErrorLabel)
                            .addGap(420, 420, 420)
                            .addComponent(sFechaErrorLabel))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(198, 198, 198)
                            .addComponent(sVolverButton)
                            .addGap(168, 168, 168)
                            .addComponent(sGuardarButton)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        camposLayout.setVerticalGroup(
            camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
            .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(camposLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26)
                    .addGap(32, 32, 32)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel19))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(sNumeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel23))
                        .addComponent(sPersonalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(4, 4, 4)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sNumeroErrorLabel)
                        .addComponent(sPersonalErrorLabel))
                    .addGap(12, 12, 12)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sPiezasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLugarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel24))))
                    .addGap(6, 6, 6)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sPiezasErrorLabel)
                        .addComponent(sLugarErrorLabel))
                    .addGap(26, 26, 26)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sCodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sEstadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel11))))
                    .addGap(6, 6, 6)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sCodigoErrorLabel)
                        .addComponent(sEstadoErrorLabel))
                    .addGap(11, 11, 11)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sFechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sFechaButton)
                        .addGroup(camposLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel25))))
                    .addGap(6, 6, 6)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sNombreErrorLabel)
                        .addComponent(sFechaErrorLabel))
                    .addGap(14, 14, 14)
                    .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sVolverButton)
                        .addComponent(sGuardarButton))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        modificarSalidasMenu.add(campos, java.awt.BorderLayout.CENTER);

        ventanas.add(modificarSalidasMenu, java.awt.BorderLayout.CENTER);

        modificarEntradasMenu.setBackground(new java.awt.Color(204, 204, 204));
        modificarEntradasMenu.setLayout(new java.awt.BorderLayout());

        campos2.setOpaque(false);

        eNumeroTextField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NUMERO:");

        ePiezasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePiezasTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("PIEZAS:");

        jLabel5.setText("CODIGO:");

        jLabel6.setText("NOMBRE:");

        eEstadoTextField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("ESTADO:");

        eProveedorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eProveedorTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("PROVEEDOR:");

        eFechaTextField.setText("DIA/MES/AÑO");
        eFechaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eFechaTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eFechaTextFieldMouseExited(evt);
            }
        });

        jLabel9.setText("FECHA:");

        eFechaButton.setText("HOY");
        eFechaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eFechaButtonActionPerformed(evt);
            }
        });

        eGuardarButton.setBackground(new java.awt.Color(153, 255, 153));
        eGuardarButton.setText("GUARDAR");
        eGuardarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eGuardarButtonMouseClicked(evt);
            }
        });

        eVolverButton.setBackground(new java.awt.Color(255, 153, 153));
        eVolverButton.setText("VOLVER");
        eVolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eVolverButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("REGISTRAR NUEVA ENTRADA");

        eNumeroErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        eNumeroErrorLabel.setText("ERROR");

        ePiezasErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        ePiezasErrorLabel.setText("ERROR");

        eCodigoErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        eCodigoErrorLabel.setText("ERROR");

        eNombreErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        eNombreErrorLabel.setText("ERROR");

        eEstadoErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        eEstadoErrorLabel.setText("ERROR");

        eProveedorErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        eProveedorErrorLabel.setText("ERROR");

        eFechaErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        eFechaErrorLabel.setText("ERROR");

        javax.swing.GroupLayout campos2Layout = new javax.swing.GroupLayout(campos2);
        campos2.setLayout(campos2Layout);
        campos2Layout.setHorizontalGroup(
            campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
            .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(campos2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addComponent(jLabel10))
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(eNumeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(eNumeroErrorLabel))
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel4)
                            .addGap(11, 11, 11)
                            .addComponent(ePiezasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(230, 230, 230)
                            .addComponent(jLabel7)
                            .addGap(6, 6, 6)
                            .addComponent(eEstadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(ePiezasErrorLabel)
                            .addGap(407, 407, 407)
                            .addComponent(eEstadoErrorLabel))
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(eCodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(200, 200, 200)
                            .addComponent(jLabel8)
                            .addGap(6, 6, 6)
                            .addComponent(eProveedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(eCodigoErrorLabel)
                            .addGap(405, 405, 405)
                            .addComponent(eProveedorErrorLabel))
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel6)
                            .addGap(11, 11, 11)
                            .addComponent(eNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(236, 236, 236)
                            .addComponent(jLabel9)
                            .addGap(6, 6, 6)
                            .addComponent(eFechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(eFechaButton))
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(eNombreErrorLabel)
                            .addGap(405, 405, 405)
                            .addComponent(eFechaErrorLabel))
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(eVolverButton)
                            .addGap(158, 158, 158)
                            .addComponent(eGuardarButton)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        campos2Layout.setVerticalGroup(
            campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(campos2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(32, 32, 32)
                    .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel3))
                        .addComponent(eNumeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(4, 4, 4)
                    .addComponent(eNumeroErrorLabel)
                    .addGap(12, 12, 12)
                    .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ePiezasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eEstadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7))))
                    .addGap(6, 6, 6)
                    .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ePiezasErrorLabel)
                        .addComponent(eEstadoErrorLabel))
                    .addGap(26, 26, 26)
                    .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eCodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eProveedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8))))
                    .addGap(6, 6, 6)
                    .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eCodigoErrorLabel)
                        .addComponent(eProveedorErrorLabel))
                    .addGap(11, 11, 11)
                    .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eFechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eFechaButton)
                        .addGroup(campos2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9))))
                    .addGap(6, 6, 6)
                    .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eNombreErrorLabel)
                        .addComponent(eFechaErrorLabel))
                    .addGap(83, 83, 83)
                    .addGroup(campos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eVolverButton)
                        .addComponent(eGuardarButton))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        modificarEntradasMenu.add(campos2, java.awt.BorderLayout.CENTER);

        ventanas.add(modificarEntradasMenu, java.awt.BorderLayout.CENTER);
        ventanas.add(jLabel12, java.awt.BorderLayout.LINE_END);
        ventanas.add(jLabel13, java.awt.BorderLayout.LINE_START);
        ventanas.add(jLabel14, java.awt.BorderLayout.PAGE_START);
        ventanas.add(jLabel15, java.awt.BorderLayout.PAGE_END);

        tabla.setOpaque(false);
        tabla.setLayout(new java.awt.BorderLayout());

        tablaStock.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaStock.setAutoscrolls(false);
        tablaStock.setRowHeight(30);
        tablaStock.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tablaStock.getTableHeader().setResizingAllowed(false);
        tablaStock.getTableHeader().setReorderingAllowed(false);
        scrollStock.setViewportView(tablaStock);

        tabla.add(scrollStock, java.awt.BorderLayout.CENTER);

        ventanas.add(tabla, java.awt.BorderLayout.CENTER);

        panelStock.add(ventanas, java.awt.BorderLayout.CENTER);

        add(panelStock, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Metodos usados para la interfaz">
    private void ePiezasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePiezasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ePiezasTextFieldActionPerformed

    private void eProveedorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eProveedorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eProveedorTextFieldActionPerformed

    private void eFechaTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eFechaTextFieldMouseEntered
        if(eFechaTextField.getText().isEmpty() || eFechaTextField.getText().isBlank() || eFechaTextField.getText().equals("DIA/MES/AÑO")){
            eFechaTextField.setText("");
        }
    }//GEN-LAST:event_eFechaTextFieldMouseEntered

    private void eFechaTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eFechaTextFieldMouseExited
        if(eFechaTextField.getText().isEmpty() || eFechaTextField.getText().isBlank()){
            eFechaTextField.setText("DIA/MES/AÑO");
        }
    }//GEN-LAST:event_eFechaTextFieldMouseExited

    private void eFechaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eFechaButtonActionPerformed
        eFechaTextField.setText(formatter.format(date));
    }//GEN-LAST:event_eFechaButtonActionPerformed

    private void eVolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eVolverButtonActionPerformed
        modificarEntradasMenu.setVisible(false);
        scrollStock.setVisible(true);
        ventanas.add(scrollStock, java.awt.BorderLayout.CENTER);
    }//GEN-LAST:event_eVolverButtonActionPerformed

    private void modificarEntradasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarEntradasButtonMouseClicked
        modificarSalidasMenu.setVisible(false);
        scrollStock.setVisible(false);
        modificarEntradasMenu.setVisible(true);
        ventanas.add(modificarEntradasMenu, java.awt.BorderLayout.CENTER);
    }//GEN-LAST:event_modificarEntradasButtonMouseClicked

    private void modificarEntradasButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarEntradasButtonMouseEntered
        modificarEntradasButton.setOpaque(true);
        repaint();
    }//GEN-LAST:event_modificarEntradasButtonMouseEntered

    private void modificarEntradasButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarEntradasButtonMouseExited
        modificarEntradasButton.setOpaque(false);
        repaint();
    }//GEN-LAST:event_modificarEntradasButtonMouseExited

    private void modificarSalidasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarSalidasButtonMouseClicked
        modificarSalidasMenu.setVisible(true);
        scrollStock.setVisible(false);
        modificarEntradasMenu.setVisible(false);
        ventanas.add(modificarSalidasMenu, java.awt.BorderLayout.CENTER);
    }//GEN-LAST:event_modificarSalidasButtonMouseClicked

    private void modificarSalidasButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarSalidasButtonMouseEntered
        modificarSalidasButton.setOpaque(true);
        repaint();
    }//GEN-LAST:event_modificarSalidasButtonMouseEntered

    private void modificarSalidasButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarSalidasButtonMouseExited
        modificarSalidasButton.setOpaque(false);
        repaint();
    }//GEN-LAST:event_modificarSalidasButtonMouseExited

    private void sPiezasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPiezasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPiezasTextFieldActionPerformed

    private void sLugarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sLugarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sLugarTextFieldActionPerformed

    private void sFechaTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sFechaTextFieldMouseEntered
        if(sFechaTextField.getText().isEmpty() || sFechaTextField.getText().isBlank() || sFechaTextField.getText().equals("DIA/MES/AÑO")){
            sFechaTextField.setText("");
        }
    }//GEN-LAST:event_sFechaTextFieldMouseEntered

    private void sFechaTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sFechaTextFieldMouseExited
        if(sFechaTextField.getText().isEmpty() || sFechaTextField.getText().isBlank()){
            sFechaTextField.setText("DIA/MES/AÑO");
        }
    }//GEN-LAST:event_sFechaTextFieldMouseExited

    private void sFechaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFechaButtonActionPerformed
        sFechaTextField.setText(formatter.format(date));
    }//GEN-LAST:event_sFechaButtonActionPerformed

    private void sVolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sVolverButtonActionPerformed
        modificarSalidasMenu.setVisible(false);
        scrollStock.setVisible(true);
        ventanas.add(scrollStock, java.awt.BorderLayout.CENTER);
    }//GEN-LAST:event_sVolverButtonActionPerformed

    private void panelStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelStockMouseClicked
        tablaStock.clearSelection();
    }//GEN-LAST:event_panelStockMouseClicked

    /*
    private void eGuardarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eGuardarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eGuardarButtonMouseClicked

    private void sGuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sGuardarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sGuardarButtonActionPerformed
    */
    
    private void manualInitComponents(){
        JTableHeader headerStock = tablaStock.getTableHeader();
	headerStock.setDefaultRenderer(new CustomHeader());
	tablaStock.setTableHeader(headerStock);
        String[] titulosStock = {"Numero","Piezas","Codigo","Nombre","Modelo","Proveedor","Estado","Observacion","Fecha"};
        Object[][] datosStock = new Object[0][0];
        modeloTablaStock = new ModeloTabla(datosStock,titulosStock, false);           
        tablaStock.getTableHeader().setBackground(new Color(64,110,36));
        tablaStock.getTableHeader().setFont(new Font("Corbel", 1, 1));
        tablaStock.setModel(modeloTablaStock);
        scrollStock.setVerticalScrollBar(new ScrollBarCustom());
        scrollStock.getVerticalScrollBar().setUnitIncrement(30);
        
        modificarEntradasMenu.setVisible(false);
        modificarSalidasMenu.setVisible(false);
        modificarSalidasButton.setSize(63, 65);
        modificarEntradasButton.setSize(63, 65);
        ponerImagen(modificarSalidasButton, "src/com/almacen/mx/view/recursos/ajustesstock.png");
        ponerImagen(modificarEntradasButton, "src/com/almacen/mx/view/recursos/ajustesstock.png");
    }
    
    private void ponerImagen(JLabel lb, String ruta) {
        ImageIcon imagen = new ImageIcon(ruta);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_SMOOTH));
        lb.setIcon(icono);
        lb.repaint();
    }
    
    private void ocultarErrores(){
        eNumeroErrorLabel.setText("");
        ePiezasErrorLabel.setText("");
        eCodigoErrorLabel.setText("");
        eNombreErrorLabel.setText("");
        eEstadoErrorLabel.setText("");
        eProveedorErrorLabel.setText("");
        eFechaErrorLabel.setText("");
        
        sNumeroErrorLabel.setText("");
        sPiezasErrorLabel.setText("");
        sCodigoErrorLabel.setText("");
        sNombreErrorLabel.setText("");
        sPersonalErrorLabel.setText("");
        sLugarErrorLabel.setText("");
        sEstadoErrorLabel.setText("");
        sFechaErrorLabel.setText("");
    }
    // </editor-fold> 
    
    //<editor-fold defaultstate="collapsed" desc="Metodos para obtener datos para Entradas">
    
    //----METODO QUE VERIFICA Y GUARDA LOS DATOS DE LAS ENTRADAS EN FORMA DE UN ARRAY DE OBJETOS----
    private void eGuardarButtonMouseClicked(java.awt.event.MouseEvent evt) {
        ocultarErrores();
        int validador = 0;
        
        Integer numero = -1, piezas = 0, codigo = 0;
        String nombre = "", estado = "", proveedor = "";
        Date fecha = new Date();
        
       validador += validarDatosNumericos(eNumeroTextField, eNumeroErrorLabel);
       validador += validarDatosNumericos(ePiezasTextField, ePiezasErrorLabel);
       validador += validarDatosNumericos(eCodigoTextField, eCodigoErrorLabel);
       
       validador += validarDatosString(eNombreTextField, eNombreErrorLabel);
       validador += validarDatosString(eEstadoTextField, eEstadoErrorLabel);
       validador += validarDatosString(eProveedorTextField, eProveedorErrorLabel);
       
       validador += validarFecha(eFechaTextField, eFechaErrorLabel);
       
       Object[] datos = new Object[7];
       
       if(validador >= 7){
           
           numero = Integer.valueOf(eNumeroTextField.getText());
           piezas = Integer.valueOf(ePiezasTextField.getText());
           codigo = Integer.valueOf(eCodigoTextField.getText());
           
           nombre = eNombreTextField.getText();
           estado = eEstadoTextField.getText();
           proveedor = eProveedorTextField.getText();
           
           try{
                fecha = formatter.parse(eFechaTextField.getText());
           } catch(Exception e){
               
           }
           
           datos[0] = numero;
           datos[1] = piezas;
           datos[2] = codigo;
           datos[3] = nombre;
           datos[4] = estado;
           datos[5] = proveedor;
           datos[6] = formatter.format(fecha);
       }
    }
    
    //----METODO QUE VERIFICA Y REGRESA LOS DATOS DE LAS SALIDAS EN FORMA DE UN ARRAY DE OBJETOS----
    private void sGuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Object[] datos = new Object[8];
        ocultarErrores();
        int validador = 0;
        
        Integer numero = 0, piezas = 0, codigo = 0;
        String nombre = "", personal = "", lugar = "", estado = "";
        Date fecha = new Date();
        
        validador += validarDatosNumericos(sNumeroTextField, sNumeroErrorLabel);
        validador += validarDatosNumericos(sPiezasTextField, sPiezasErrorLabel);
        validador += validarDatosNumericos(sCodigoTextField, sCodigoErrorLabel);
        validador += validarDatosString(sNombreTextField, sNombreErrorLabel);
        validador += validarDatosString(sPersonalTextField, sPersonalErrorLabel);
        validador += validarDatosString(sLugarTextField, sLugarErrorLabel);
        validador += validarDatosString(sEstadoTextField, sEstadoErrorLabel);
        validador += validarFecha(sFechaTextField, sFechaErrorLabel);
        
        if(validador >= 8){
           numero = Integer.valueOf(sNumeroTextField.getText());
           piezas = Integer.valueOf(sPiezasTextField.getText());
           codigo = Integer.valueOf(sCodigoTextField.getText());
           
           nombre = eNombreTextField.getText();
           personal = sPersonalTextField.getText();
           lugar = sLugarTextField.getText();
           estado = sEstadoTextField.getText();
           
           try{
                fecha = formatter.parse(sFechaTextField.getText());
           } catch(Exception e){
               
           }
           
           datos[0] = numero;
           datos[1] = piezas;
           datos[2] = codigo;
           datos[3] = nombre;
           datos[4] = personal;
           datos[5] = lugar;
           datos[6] = estado;
           datos[7] = formatter.format(fecha);
        }
    }       
    
    private int validarDatosNumericos(JTextField textfield, JLabel errorLabel){
        int validador = 1;
        int numero;
        if(textfield.getText().isBlank() || textfield.getText().isBlank()){
            validador = 0;
            errorLabel.setText("CAMPO VACIO");
        } else {
            try{
                numero = parseInt(textfield.getText());
            } catch(NumberFormatException e){
                errorLabel.setText("SOLO NUMEROS");
                validador = 0;
            }
        }
        return validador;
    }
    
    private int validarDatosString(JTextField textfield, JLabel errorLabel){
        int validador = 1;
        if(textfield.getText().isBlank() || textfield.getText().isEmpty()){
            validador = 0;
            errorLabel.setText("CAMPO VACIO");
        }
        return validador;
    }
    
    private int validarFecha(JTextField textfield, JLabel errorLabel){
        int validador = 1;
        try{
           formatter.parse(eFechaTextField.getText());
        }catch(Exception e){
            validador = 0;
            errorLabel.setText("FORMATO NO VALIDO");
        }
        if(textfield.getText().isBlank() || textfield.getText().isEmpty()){
            validador = 0;
            errorLabel.setText("CAMPO VACIO");
        }
        return validador;
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botones;
    private javax.swing.JPanel campos;
    private javax.swing.JPanel campos2;
    private javax.swing.JPanel centro;
    private javax.swing.JLabel eCodigoErrorLabel;
    private javax.swing.JTextField eCodigoTextField;
    private javax.swing.JLabel eEstadoErrorLabel;
    private javax.swing.JTextField eEstadoTextField;
    private javax.swing.JButton eFechaButton;
    private javax.swing.JLabel eFechaErrorLabel;
    private javax.swing.JTextField eFechaTextField;
    private javax.swing.JButton eGuardarButton;
    private javax.swing.JLabel eNombreErrorLabel;
    private javax.swing.JTextField eNombreTextField;
    private javax.swing.JLabel eNumeroErrorLabel;
    private javax.swing.JTextField eNumeroTextField;
    private javax.swing.JLabel ePiezasErrorLabel;
    private javax.swing.JTextField ePiezasTextField;
    private javax.swing.JLabel eProveedorErrorLabel;
    private javax.swing.JTextField eProveedorTextField;
    private javax.swing.JButton eVolverButton;
    private javax.swing.JPanel entradas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel meLabel;
    private javax.swing.JLabel modificarEntradasButton;
    private javax.swing.JPanel modificarEntradasMenu;
    private javax.swing.JLabel modificarSalidasButton;
    private javax.swing.JPanel modificarSalidasMenu;
    private javax.swing.JLabel msLabel;
    private javax.swing.JPanel panelStock;
    private javax.swing.JLabel sCodigoErrorLabel;
    private javax.swing.JTextField sCodigoTextField;
    private javax.swing.JLabel sEstadoErrorLabel;
    private javax.swing.JTextField sEstadoTextField;
    private javax.swing.JButton sFechaButton;
    private javax.swing.JLabel sFechaErrorLabel;
    private javax.swing.JTextField sFechaTextField;
    private javax.swing.JButton sGuardarButton;
    private javax.swing.JLabel sLugarErrorLabel;
    private javax.swing.JTextField sLugarTextField;
    private javax.swing.JLabel sNombreErrorLabel;
    private javax.swing.JTextField sNombreTextField;
    private javax.swing.JLabel sNumeroErrorLabel;
    private javax.swing.JTextField sNumeroTextField;
    private javax.swing.JLabel sPersonalErrorLabel;
    private javax.swing.JTextField sPersonalTextField;
    private javax.swing.JLabel sPiezasErrorLabel;
    private javax.swing.JTextField sPiezasTextField;
    private javax.swing.JButton sVolverButton;
    private javax.swing.JPanel salidas;
    private javax.swing.JScrollPane scrollStock;
    private javax.swing.JPanel tabla;
    private javax.swing.JTable tablaStock;
    private javax.swing.JPanel ventanas;
    // End of variables declaration//GEN-END:variables
    Date date = new Date();
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yy"); 
    DefaultTableModel modeloTablaStock;
    //</editor-fold>
}
