/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.almacen.mx.view.aplicaciondepartamentomantenimiento;

import com.almacen.mx.view.aplicaciondepartamentomantenimiento.customUI.CustomHeader;
import aplicaciondepartamentomantenimiento.customUI.ScrollBarCustom;
import com.almacen.mx.view.aplicaciondepartamentomantenimiento.customUI.ModeloTabla;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import static java.lang.Integer.parseInt;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author acost
 */
public class StockMenu extends javax.swing.JPanel {

    /**
     * Creates new form StockMenu
     */
    public StockMenu() {
        initComponents();       
        manualInitComponents();
        ventanas.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStock = new javax.swing.JPanel();
        botones = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        entradas = new javax.swing.JPanel();
        meLabel = new javax.swing.JLabel();
        modificarEntradasButton = new javax.swing.JLabel();
        salidas = new javax.swing.JPanel();
        msLabel = new javax.swing.JLabel();
        modificarSalidasButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ventanas = new javax.swing.JTabbedPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelStock.setBackground(new java.awt.Color(44, 60, 67));
        panelStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelStockMouseClicked(evt);
            }
        });
        panelStock.setLayout(new java.awt.BorderLayout(30, 20));

        botones.setOpaque(false);
        botones.setPreferredSize(new java.awt.Dimension(510, 130));
        botones.setLayout(new java.awt.BorderLayout(300, 0));

        centro.setMaximumSize(new java.awt.Dimension(500, 130));
        centro.setOpaque(false);
        centro.setPreferredSize(new java.awt.Dimension(210, 130));
        centro.setLayout(new java.awt.BorderLayout());

        entradas.setOpaque(false);
        entradas.setPreferredSize(new java.awt.Dimension(110, 100));
        entradas.setLayout(new java.awt.BorderLayout());

        meLabel.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        meLabel.setForeground(new java.awt.Color(255, 255, 255));
        meLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meLabel.setText("<HTML><center>AGREGAR <p> ENTRADAS");
        meLabel.setPreferredSize(new java.awt.Dimension(81, 30));
        entradas.add(meLabel, java.awt.BorderLayout.PAGE_START);

        modificarEntradasButton.setBackground(new java.awt.Color(0, 51, 51));
        modificarEntradasButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificarEntradasButton.setPreferredSize(new java.awt.Dimension(50, 50));
        modificarEntradasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarEntradasButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarEntradasButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarEntradasButtonMouseExited(evt);
            }
        });
        entradas.add(modificarEntradasButton, java.awt.BorderLayout.CENTER);

        centro.add(entradas, java.awt.BorderLayout.WEST);

        salidas.setOpaque(false);
        salidas.setPreferredSize(new java.awt.Dimension(110, 100));
        salidas.setLayout(new java.awt.BorderLayout());

        msLabel.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        msLabel.setForeground(new java.awt.Color(255, 255, 255));
        msLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msLabel.setText("<HTML><center>AGREGAR <p> SALIDAS");
        msLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salidas.add(msLabel, java.awt.BorderLayout.PAGE_START);

        modificarSalidasButton.setBackground(new java.awt.Color(0, 51, 51));
        modificarSalidasButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificarSalidasButton.setPreferredSize(new java.awt.Dimension(50, 50));
        modificarSalidasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarSalidasButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarSalidasButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarSalidasButtonMouseExited(evt);
            }
        });
        salidas.add(modificarSalidasButton, java.awt.BorderLayout.CENTER);

        centro.add(salidas, java.awt.BorderLayout.EAST);

        botones.add(centro, java.awt.BorderLayout.CENTER);
        botones.add(jLabel1, java.awt.BorderLayout.WEST);
        botones.add(jLabel2, java.awt.BorderLayout.EAST);

        panelStock.add(botones, java.awt.BorderLayout.PAGE_END);
        panelStock.add(ventanas, java.awt.BorderLayout.CENTER);
        panelStock.add(jLabel12, java.awt.BorderLayout.PAGE_START);
        panelStock.add(jLabel13, java.awt.BorderLayout.LINE_END);
        panelStock.add(jLabel14, java.awt.BorderLayout.LINE_START);

        add(panelStock, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Metodos Interfaz">
    private void panelStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelStockMouseClicked
        
    }//GEN-LAST:event_panelStockMouseClicked

    private void modificarSalidasButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarSalidasButtonMouseExited
        modificarSalidasButton.setOpaque(false);
        repaint();
    }//GEN-LAST:event_modificarSalidasButtonMouseExited
    
    private void eMedidaTextFieldActionPerformed(java.awt.event.ActionEvent evt){
        
    }
    
    private void modificarSalidasButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarSalidasButtonMouseEntered
        modificarSalidasButton.setOpaque(true);
        repaint();
    }//GEN-LAST:event_modificarSalidasButtonMouseEntered

    private void modificarSalidasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarSalidasButtonMouseClicked
        ventanas.setSelectedIndex(1);
    }//GEN-LAST:event_modificarSalidasButtonMouseClicked

    private void modificarEntradasButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarEntradasButtonMouseExited
        modificarEntradasButton.setOpaque(false);
        repaint();
    }//GEN-LAST:event_modificarEntradasButtonMouseExited

    private void modificarEntradasButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarEntradasButtonMouseEntered
        modificarEntradasButton.setOpaque(true);
        repaint();
    }//GEN-LAST:event_modificarEntradasButtonMouseEntered
    
    public static void volverStock(){
        ventanas.setSelectedIndex(0);
    }
    
    private void modificarEntradasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarEntradasButtonMouseClicked
        ventanas.setSelectedIndex(2);
    }//GEN-LAST:event_modificarEntradasButtonMouseClicked
       
    private void manualInitComponents(){       
        modificarSalidasButton.setSize(63, 65);
        modificarEntradasButton.setSize(63, 65);
        ponerImagen(modificarSalidasButton, "src/com/almacen/mx/view/recursos/ajustesstock.png");
        ponerImagen(modificarEntradasButton, "src/com/almacen/mx/view/recursos/ajustesstock.png");
        
        ventanas.add(tabla);
        ventanas.add(salidasStock);
        ventanas.add(entradasStock);
        
        ventanas.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0;

            }
             @Override
            protected void installDefaults() {
                super.installDefaults();
                tabAreaInsets = new Insets(0, 0, 0, 0);
                contentBorderInsets = new Insets(0, 0, 0, 0);
            }
        });
    }
    
    private void ponerImagen(JLabel lb, String ruta) {
        ImageIcon imagen = new ImageIcon(ruta);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_SMOOTH));
        lb.setIcon(icono);
        lb.repaint();
    }      
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botones;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel entradas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel meLabel;
    private javax.swing.JLabel modificarEntradasButton;
    private javax.swing.JLabel modificarSalidasButton;
    private javax.swing.JLabel msLabel;
    private javax.swing.JPanel panelStock;
    private javax.swing.JPanel salidas;
    public static javax.swing.JTabbedPane ventanas;
    // End of variables declaration//GEN-END:variables
   private final tablaStockMenu tabla = new tablaStockMenu();
   private final SalidasStockMenu salidasStock = new SalidasStockMenu();
   private final EntradaStockMenu entradasStock = new EntradaStockMenu();
    //</editor-fold>
}
