/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.almacen.mx.view.aplicaciondepartamentomantenimiento;

import aplicaciondepartamentomantenimiento.customUI.ScrollBarCustom;
import com.almacen.mx.bo.StockBO;
import com.almacen.mx.view.aplicaciondepartamentomantenimiento.customUI.CustomHeader;
import com.almacen.mx.view.aplicaciondepartamentomantenimiento.customUI.ModeloTabla;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author acost
 */
public class tablaStockMenu extends javax.swing.JPanel {

    /**
     * Creates new form tablaStockMenu
     */
    public tablaStockMenu() {
        initComponents();
        manualInitComponents();
        
        StockBO sbo = new StockBO();
        
        sbo.listarStockID(tablaStock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabla = new javax.swing.JPanel();
        scrollStock = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 60, 67));
        setLayout(new java.awt.BorderLayout());

        tabla.setOpaque(false);
        tabla.setLayout(new java.awt.BorderLayout(10, 10));

        tablaStock.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaStock.setAutoscrolls(false);
        tablaStock.setRowHeight(30);
        tablaStock.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tablaStock.getTableHeader().setResizingAllowed(false);
        tablaStock.getTableHeader().setReorderingAllowed(false);
        scrollStock.setViewportView(tablaStock);

        tabla.add(scrollStock, java.awt.BorderLayout.CENTER);
        tabla.add(jLabel1, java.awt.BorderLayout.PAGE_START);
        tabla.add(jLabel2, java.awt.BorderLayout.LINE_START);
        tabla.add(jLabel3, java.awt.BorderLayout.LINE_END);
        tabla.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        add(tabla, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    private void manualInitComponents(){
        JTableHeader headerStock = tablaStock.getTableHeader();
	headerStock.setDefaultRenderer(new CustomHeader());
	tablaStock.setTableHeader(headerStock);       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane scrollStock;
    private javax.swing.JPanel tabla;
    private javax.swing.JTable tablaStock;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel modeloTablaStock;
}
