/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicaciondepartamentomantenimiento;

import aplicaciondepartamentomantenimiento.customUI.CustomHeader;
import aplicaciondepartamentomantenimiento.customUI.ModeloTabla;
import aplicaciondepartamentomantenimiento.customUI.ScrollBarCustom;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


/**
 *
 * @author Jerenis Acosta
 */
public class Ventana extends javax.swing.JFrame {

    //Iniciador de la ventana
    public Ventana() {
        initComponents();
        manualInitComponents();
        this.setLocationRelativeTo(this);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        barraSuperior = new javax.swing.JPanel();
        botonMinimizar = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JLabel();
        labelMenuActual = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        scrollPanelMenu = new javax.swing.JScrollPane();
        panelMenu = new javax.swing.JPanel();
        entradaMBoton = new javax.swing.JLabel();
        salidaMboton = new javax.swing.JLabel();
        stockBoton = new javax.swing.JLabel();
        proveedoresBoton = new javax.swing.JLabel();
        personalBoton = new javax.swing.JLabel();
        cotizacionBoton = new javax.swing.JLabel();
        seguimientoBoton = new javax.swing.JLabel();
        cierreMBoton = new javax.swing.JLabel();
        articulosBoton = new javax.swing.JLabel();
        ordenBoton = new javax.swing.JLabel();
        observacionesBoton = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JTabbedPane();
        panelEntrada = new javax.swing.JPanel();
        scrollEntradas = new javax.swing.JScrollPane();
        tablaEntradas = new javax.swing.JTable();
        botonAñadirEntrada = new javax.swing.JButton();
        botonEliminarEntrada = new javax.swing.JButton();
        botonGuardarEntrada = new javax.swing.JButton();
        panelSalida = new javax.swing.JPanel();
        scrollSalida = new javax.swing.JScrollPane();
        tablaSalida = new javax.swing.JTable();
        botonAñadirSalida = new javax.swing.JButton();
        botonEliminarSalida = new javax.swing.JButton();
        botonGuardarSalida = new javax.swing.JButton();
        panelStock = new javax.swing.JPanel();
        scrollStock = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        ajustesboton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelProveedores = new javax.swing.JPanel();
        labelProveedores = new javax.swing.JLabel();
        panelPersonal = new javax.swing.JPanel();
        labelPersonal = new javax.swing.JLabel();
        panelCotizacion = new javax.swing.JPanel();
        labelCotizacion = new javax.swing.JLabel();
        panelSeguimiento = new javax.swing.JPanel();
        labelSeguimiento = new javax.swing.JLabel();
        panelMenuPrincipal = new javax.swing.JPanel();
        logoITS = new javax.swing.JLabel();
        textoInstitucion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("ventana"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 920));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(44, 60, 67));
        panelPrincipal.setForeground(new java.awt.Color(255, 51, 0));
        panelPrincipal.setName("panelPrincipal"); // NOI18N
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 920));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraSuperior.setBackground(new java.awt.Color(64, 110, 36));
        barraSuperior.setAutoscrolls(true);
        barraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraSuperiorMouseDragged(evt);
            }
        });
        barraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraSuperiorMousePressed(evt);
            }
        });
        barraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMinimizar.setBackground(new java.awt.Color(241, 46, 101));
        botonMinimizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonMinimizar.setText("-");
        botonMinimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMinimizar.setOpaque(true);
        botonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseExited(evt);
            }
        });
        barraSuperior.add(botonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 30, 20));

        botonCerrar.setBackground(new java.awt.Color(241, 46, 101));
        botonCerrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonCerrar.setText("X");
        botonCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCerrar.setOpaque(true);
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCerrarMouseExited(evt);
            }
        });
        barraSuperior.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 30, 20));
        botonCerrar.getAccessibleContext().setAccessibleName("");

        labelMenuActual.setBackground(new java.awt.Color(0, 102, 0));
        labelMenuActual.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        labelMenuActual.setForeground(new java.awt.Color(255, 255, 255));
        labelMenuActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenuActual.setText("<html><center>TEXTO");
        labelMenuActual.setAutoscrolls(true);
        labelMenuActual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelMenuActual.setOpaque(true);
        labelMenuActual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraSuperior.add(labelMenuActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 190, 40));
        labelMenuActual.getAccessibleContext().setAccessibleName("FECHA");

        labelFecha.setBackground(new java.awt.Color(0, 102, 0));
        labelFecha.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFecha.setText("<html><center>FECHA");
        labelFecha.setAutoscrolls(true);
        labelFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelFecha.setOpaque(true);
        labelFecha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraSuperior.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        panelPrincipal.add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        scrollPanelMenu.setBackground(new java.awt.Color(0, 153, 51));
        scrollPanelMenu.setPreferredSize(new java.awt.Dimension(80, 1000));

        panelMenu.setBackground(new java.awt.Color(119, 168, 37));
        panelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMenu.setMinimumSize(new java.awt.Dimension(150, 0));
        panelMenu.setPreferredSize(new java.awt.Dimension(10, 2430));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaMBoton.setBackground(new java.awt.Color(102, 153, 0));
        entradaMBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entradaMBoton.setToolTipText("");
        entradaMBoton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        entradaMBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        entradaMBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        entradaMBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradaMBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entradaMBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entradaMBotonMouseExited(evt);
            }
        });
        panelMenu.add(entradaMBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 140));
        entradaMBoton.getAccessibleContext().setAccessibleName("entrada");

        salidaMboton.setBackground(new java.awt.Color(102, 153, 0));
        salidaMboton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salidaMboton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salidaMboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salidaMbotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salidaMbotonMouseExited(evt);
            }
        });
        panelMenu.add(salidaMboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 140));
        salidaMboton.getAccessibleContext().setAccessibleName("salida");

        stockBoton.setBackground(new java.awt.Color(102, 153, 0));
        stockBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stockBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockBotonMouseEntered(evt);
            }
        });
        panelMenu.add(stockBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 140, 140));
        stockBoton.getAccessibleContext().setAccessibleName("stock");

        proveedoresBoton.setBackground(new java.awt.Color(102, 153, 0));
        proveedoresBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proveedoresBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(proveedoresBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 140, 140));
        proveedoresBoton.getAccessibleContext().setAccessibleName("proveedores");

        personalBoton.setBackground(new java.awt.Color(102, 153, 0));
        personalBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(personalBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 890, 140, 140));
        personalBoton.getAccessibleContext().setAccessibleName("personal");

        cotizacionBoton.setBackground(new java.awt.Color(102, 153, 0));
        cotizacionBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cotizacionBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(cotizacionBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1110, 140, 140));
        cotizacionBoton.getAccessibleContext().setAccessibleName("cotizacion");

        seguimientoBoton.setBackground(new java.awt.Color(102, 153, 0));
        seguimientoBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seguimientoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(seguimientoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1330, 140, 140));
        seguimientoBoton.getAccessibleContext().setAccessibleName("seguimiento");

        cierreMBoton.setBackground(new java.awt.Color(102, 153, 0));
        cierreMBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cierreMBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(cierreMBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1550, 140, 140));

        articulosBoton.setBackground(new java.awt.Color(102, 153, 0));
        articulosBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        articulosBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(articulosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1770, 140, 140));

        ordenBoton.setBackground(new java.awt.Color(102, 153, 0));
        ordenBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordenBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(ordenBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1990, 140, 140));

        observacionesBoton.setBackground(new java.awt.Color(102, 153, 0));
        observacionesBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        observacionesBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(observacionesBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2210, 140, 140));

        label1.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(44, 60, 67));
        label1.setText("<html><center>Entrada de  <p> material");
        panelMenu.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, -1));

        label2.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(44, 60, 67));
        label2.setText("<html><center>Salida de  <p> material");
        panelMenu.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, -1));

        label3.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        label3.setForeground(new java.awt.Color(44, 60, 67));
        label3.setText("<html><center>Stock");
        panelMenu.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 110, -1));

        label4.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        label4.setForeground(new java.awt.Color(44, 60, 67));
        label4.setText("<html><center>Proveedores");
        panelMenu.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, 130, -1));

        label5.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        label5.setForeground(new java.awt.Color(44, 60, 67));
        label5.setText("<html><center>Personal");
        panelMenu.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1030, 110, -1));

        label6.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        label6.setForeground(new java.awt.Color(44, 60, 67));
        label6.setText("<html><center>Cotizacion");
        panelMenu.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 1250, 110, -1));

        label7.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        label7.setForeground(new java.awt.Color(44, 60, 67));
        label7.setText("<html><center>Seguimiento");
        panelMenu.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1460, 130, 40));

        scrollPanelMenu.setViewportView(panelMenu);

        panelPrincipal.add(scrollPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 900));

        panelContenedor.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        panelContenedor.setMinimumSize(new java.awt.Dimension(81, 125));

        panelEntrada.setBackground(new java.awt.Color(44, 60, 67));
        panelEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEntradaMouseClicked(evt);
            }
        });

        scrollEntradas.setBackground(new java.awt.Color(40, 60, 67));

        tablaEntradas.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Piezas", "Codigo", "Nombre", "Estado", "Proveedor", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEntradas.setGridColor(new java.awt.Color(40, 60, 67));
        tablaEntradas.setRowHeight(30);
        tablaEntradas.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tablaEntradas.getTableHeader().setResizingAllowed(false);
        tablaEntradas.getTableHeader().setReorderingAllowed(false);
        scrollEntradas.setViewportView(tablaEntradas);
        if (tablaEntradas.getColumnModel().getColumnCount() > 0) {
            tablaEntradas.getColumnModel().getColumn(0).setResizable(false);
            tablaEntradas.getColumnModel().getColumn(1).setResizable(false);
            tablaEntradas.getColumnModel().getColumn(2).setResizable(false);
            tablaEntradas.getColumnModel().getColumn(3).setResizable(false);
            tablaEntradas.getColumnModel().getColumn(4).setResizable(false);
            tablaEntradas.getColumnModel().getColumn(5).setResizable(false);
            tablaEntradas.getColumnModel().getColumn(6).setResizable(false);
        }

        botonAñadirEntrada.setBackground(new java.awt.Color(119, 168, 37));
        botonAñadirEntrada.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        botonAñadirEntrada.setText("AÑADIR");
        botonAñadirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirEntradaActionPerformed(evt);
            }
        });

        botonEliminarEntrada.setBackground(new java.awt.Color(255, 102, 102));
        botonEliminarEntrada.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        botonEliminarEntrada.setText("ELIMINAR");
        botonEliminarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEliminarEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEliminarEntradaMouseExited(evt);
            }
        });
        botonEliminarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEntradaActionPerformed(evt);
            }
        });

        botonGuardarEntrada.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        botonGuardarEntrada.setText("GUARDAR");
        botonGuardarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEntradaLayout = new javax.swing.GroupLayout(panelEntrada);
        panelEntrada.setLayout(panelEntradaLayout);
        panelEntradaLayout.setHorizontalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(botonAñadirEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardarEntrada)
                .addGap(273, 273, 273)
                .addComponent(botonEliminarEntrada)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(scrollEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelEntradaLayout.setVerticalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scrollEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAñadirEntrada)
                    .addComponent(botonGuardarEntrada)
                    .addComponent(botonEliminarEntrada))
                .addGap(61, 61, 61))
        );

        panelContenedor.addTab("tab1", panelEntrada);

        panelSalida.setBackground(new java.awt.Color(44, 60, 67));
        panelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSalidaMouseClicked(evt);
            }
        });

        tablaSalida.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSalida.setRowHeight(30);
        tablaSalida.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tablaSalida.getTableHeader().setResizingAllowed(false);
        tablaSalida.getTableHeader().setReorderingAllowed(false);
        scrollSalida.setViewportView(tablaSalida);

        botonAñadirSalida.setBackground(new java.awt.Color(119, 168, 37));
        botonAñadirSalida.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        botonAñadirSalida.setText("AÑADIR");
        botonAñadirSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirSalidaActionPerformed(evt);
            }
        });

        botonEliminarSalida.setBackground(new java.awt.Color(255, 102, 102));
        botonEliminarSalida.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        botonEliminarSalida.setText("ELIMINAR");
        botonEliminarSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEliminarSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEliminarSalidaMouseExited(evt);
            }
        });
        botonEliminarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSalidaActionPerformed(evt);
            }
        });

        botonGuardarSalida.setText("GUARDAR");

        javax.swing.GroupLayout panelSalidaLayout = new javax.swing.GroupLayout(panelSalida);
        panelSalida.setLayout(panelSalidaLayout);
        panelSalidaLayout.setHorizontalGroup(
            panelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalidaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(scrollSalida)
                .addContainerGap())
            .addGroup(panelSalidaLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(botonAñadirSalida)
                .addGap(305, 305, 305)
                .addComponent(botonGuardarSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(botonEliminarSalida)
                .addGap(93, 93, 93))
        );
        panelSalidaLayout.setVerticalGroup(
            panelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalidaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAñadirSalida)
                    .addComponent(botonEliminarSalida)
                    .addComponent(botonGuardarSalida))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        panelContenedor.addTab("tab2", panelSalida);

        panelStock.setBackground(new java.awt.Color(44, 60, 67));
        panelStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelStockMouseClicked(evt);
            }
        });

        tablaStock.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaStock.setAutoscrolls(false);
        tablaStock.setRowHeight(30);
        tablaStock.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tablaStock.getTableHeader().setResizingAllowed(false);
        tablaStock.getTableHeader().setReorderingAllowed(false);
        scrollStock.setViewportView(tablaStock);
        if (tablaStock.getColumnModel().getColumnCount() > 0) {
            tablaStock.getColumnModel().getColumn(0).setResizable(false);
            tablaStock.getColumnModel().getColumn(1).setResizable(false);
            tablaStock.getColumnModel().getColumn(2).setResizable(false);
            tablaStock.getColumnModel().getColumn(3).setResizable(false);
        }

        ajustesboton.setBackground(new java.awt.Color(44, 60, 67));
        ajustesboton.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AJUSTES");

        javax.swing.GroupLayout panelStockLayout = new javax.swing.GroupLayout(panelStock);
        panelStock.setLayout(panelStockLayout);
        panelStockLayout.setHorizontalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStockLayout.createSequentialGroup()
                .addGroup(panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStockLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(scrollStock, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStockLayout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addGroup(panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelStockLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(ajustesboton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelStockLayout.setVerticalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStockLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(scrollStock, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ajustesboton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panelContenedor.addTab("tab3", panelStock);

        panelProveedores.setBackground(new java.awt.Color(44, 60, 67));

        javax.swing.GroupLayout panelProveedoresLayout = new javax.swing.GroupLayout(panelProveedores);
        panelProveedores.setLayout(panelProveedoresLayout);
        panelProveedoresLayout.setHorizontalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(labelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        panelProveedoresLayout.setVerticalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(labelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panelContenedor.addTab("tab4", panelProveedores);

        panelPersonal.setBackground(new java.awt.Color(44, 60, 67));

        javax.swing.GroupLayout panelPersonalLayout = new javax.swing.GroupLayout(panelPersonal);
        panelPersonal.setLayout(panelPersonalLayout);
        panelPersonalLayout.setHorizontalGroup(
            panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalLayout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(labelPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );
        panelPersonalLayout.setVerticalGroup(
            panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(labelPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        panelContenedor.addTab("tab5", panelPersonal);

        panelCotizacion.setBackground(new java.awt.Color(44, 60, 67));

        javax.swing.GroupLayout panelCotizacionLayout = new javax.swing.GroupLayout(panelCotizacion);
        panelCotizacion.setLayout(panelCotizacionLayout);
        panelCotizacionLayout.setHorizontalGroup(
            panelCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCotizacionLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(labelCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
        );
        panelCotizacionLayout.setVerticalGroup(
            panelCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCotizacionLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(labelCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        panelContenedor.addTab("tab6", panelCotizacion);

        panelSeguimiento.setBackground(new java.awt.Color(44, 60, 67));

        javax.swing.GroupLayout panelSeguimientoLayout = new javax.swing.GroupLayout(panelSeguimiento);
        panelSeguimiento.setLayout(panelSeguimientoLayout);
        panelSeguimientoLayout.setHorizontalGroup(
            panelSeguimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeguimientoLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(labelSeguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        panelSeguimientoLayout.setVerticalGroup(
            panelSeguimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeguimientoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelSeguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelContenedor.addTab("tab7", panelSeguimiento);

        panelMenuPrincipal.setBackground(new java.awt.Color(44, 60, 67));

        textoInstitucion.setFont(new java.awt.Font("Corbel", 1, 48)); // NOI18N
        textoInstitucion.setForeground(new java.awt.Color(255, 255, 255));
        textoInstitucion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoInstitucion.setText("INSTITUTO TECNOLOGICO DE SALTILLO");
        textoInstitucion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><center>Departamento de Mantenimiento <p>Y prevencion");

        javax.swing.GroupLayout panelMenuPrincipalLayout = new javax.swing.GroupLayout(panelMenuPrincipal);
        panelMenuPrincipal.setLayout(panelMenuPrincipalLayout);
        panelMenuPrincipalLayout.setHorizontalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPrincipalLayout.createSequentialGroup()
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoInstitucion, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPrincipalLayout.createSequentialGroup()
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2)
                            .addComponent(logoITS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(268, 268, 268))))
        );
        panelMenuPrincipalLayout.setVerticalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(logoITS, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        panelContenedor.addTab("tab8", panelMenuPrincipal);

        panelPrincipal.add(panelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 1110, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseEntered
        botonCerrar.setBackground(new Color(241,200,200));
    }//GEN-LAST:event_botonCerrarMouseEntered

    private void botonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseExited
        botonCerrar.setBackground(new Color(241,46,101));
    }//GEN-LAST:event_botonCerrarMouseExited

    private void entradaMBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradaMBotonMouseEntered
        entradaMBoton.setOpaque(true);
        repaint();  
    }//GEN-LAST:event_entradaMBotonMouseEntered

    private void entradaMBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradaMBotonMouseExited
        entradaMBoton.setOpaque(false);
        repaint();
    }//GEN-LAST:event_entradaMBotonMouseExited

    private void entradaMBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradaMBotonMouseClicked

    }//GEN-LAST:event_entradaMBotonMouseClicked

    private void salidaMbotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidaMbotonMouseEntered
        salidaMboton.setOpaque(true);
        repaint();
    }//GEN-LAST:event_salidaMbotonMouseEntered

    private void salidaMbotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidaMbotonMouseExited
        salidaMboton.setOpaque(false);
        repaint();
    }//GEN-LAST:event_salidaMbotonMouseExited

    private void stockBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockBotonMouseEntered
        
    }//GEN-LAST:event_stockBotonMouseEntered
    
    private void barraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraSuperiorMouseDragged

    private void barraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraSuperiorMousePressed

    private void botonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseClicked
        this.setExtendedState(Ventana.ICONIFIED);
    }//GEN-LAST:event_botonMinimizarMouseClicked

    private void botonMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseEntered
        botonMinimizar.setBackground(new Color(241,200,200));
    }//GEN-LAST:event_botonMinimizarMouseEntered

    private void botonMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseExited
        botonMinimizar.setBackground(new Color(241,46,101));
    }//GEN-LAST:event_botonMinimizarMouseExited

    private void botonAñadirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirEntradaActionPerformed
        String[] s = new String[7];    
        s[6] = formatter.format(date);
        modeloTablaEntrada.addRow(s);
        
    }//GEN-LAST:event_botonAñadirEntradaActionPerformed

    private void botonEliminarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEntradaActionPerformed
        if(tablaEntradas.getSelectedRow() >= 0){
            int l = tablaEntradas.getSelectedRows().length;
            for(int i = 0; i <= l-1;i++){
            modeloTablaEntrada.removeRow(tablaEntradas.getSelectedRow());
            }
        }    
    }//GEN-LAST:event_botonEliminarEntradaActionPerformed

    private void botonEliminarEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarEntradaMouseEntered
        tablaEntradas.setSelectionBackground(Color.RED);
    }//GEN-LAST:event_botonEliminarEntradaMouseEntered

    private void botonEliminarEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarEntradaMouseExited
        tablaEntradas.setSelectionBackground(new Color(0,204,102));
    }//GEN-LAST:event_botonEliminarEntradaMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void panelEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntradaMouseClicked
        tablaEntradas.clearSelection();
    }//GEN-LAST:event_panelEntradaMouseClicked

    private void botonGuardarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarEntradaActionPerformed

    private void botonAñadirSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirSalidaActionPerformed
        String[] s = new String[8];    
        s[7] = formatter.format(date);
        modeloTablaSalida.addRow(s);
    }//GEN-LAST:event_botonAñadirSalidaActionPerformed

    private void botonEliminarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSalidaActionPerformed
        if(tablaSalida.getSelectedRow() >= 0){
            int l = tablaSalida.getSelectedRows().length;
            for(int i = 0; i <= l-1;i++){
            modeloTablaSalida.removeRow(tablaSalida.getSelectedRow());
            }
        }    
    }//GEN-LAST:event_botonEliminarSalidaActionPerformed

    private void botonEliminarSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarSalidaMouseEntered
        tablaSalida.setSelectionBackground(Color.red);
    }//GEN-LAST:event_botonEliminarSalidaMouseEntered

    private void botonEliminarSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarSalidaMouseExited
       tablaSalida.setSelectionBackground(new Color(0,204,102));
    }//GEN-LAST:event_botonEliminarSalidaMouseExited

    private void panelSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalidaMouseClicked
        tablaSalida.clearSelection();
    }//GEN-LAST:event_panelSalidaMouseClicked

    private void panelStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelStockMouseClicked
        tablaStock.clearSelection();
    }//GEN-LAST:event_panelStockMouseClicked
    
    private void botonesMenuMouseEntered(MouseEvent evt){
        JLabel boton = (JLabel)evt.getSource();
        boton.setOpaque(true);
        repaint();
    }
    
    private void botonesMenuMouseExited(MouseEvent evt){
        JLabel boton = (JLabel)evt.getSource();
        boton.setOpaque(false);
        repaint();
    }   
    
    private void botonesMenuClicked(MouseEvent evt){      
        for(int i = 0; i < botonesMenu.length; i++){
            if(evt.getSource().equals(botonesMenu[i])){
                panelContenedor.setSelectedIndex(i);
            }
        }
    }
    
    private void manualInitComponents(){
        //<editor-fold defaultstate="collapsed" desc="Menu Principal code">
        ponerImagen(entradaMBoton, "src/recursos/entradaMLogo.png");
        ponerImagen(salidaMboton, "src/recursos/salidaMlogo.png");
        ponerImagen(stockBoton, "src/recursos/stocklogo.png");
        ponerImagen(proveedoresBoton, "src/recursos/proveedoreslogo.png");
        ponerImagen(personalBoton, "src/recursos/personallogo.png");
        ponerImagen(cotizacionBoton, "src/recursos/cotizacionlogo.png");
        ponerImagen(seguimientoBoton, "src/recursos/seguimientologo.png");
        ponerImagen(cierreMBoton, "src/recursos/cierrelogo.png");
        ponerImagen(articulosBoton, "src/recursos/articuloslogo.png");
        ponerImagen(ordenBoton, "src/recursos/ordenlogo.png");
        ponerImagen(observacionesBoton, "src/recursos/observacioneslogo.png");
        ponerImagen(logoITS, "src/recursos/logotec.png");
        ponerImagen(ajustesboton, "src/recursos/ajustesstock.png");
                        
        maBotonesMenu = new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                botonesMenuMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                botonesMenuMouseExited(evt);
            }          
            public void mouseClicked(MouseEvent evt){
                JLabel e = (JLabel)evt.getSource();
                if(e.equals(entradaMBoton)){
                    panelContenedor.setSelectedIndex(0);
                    labelMenuActual.setText("Entrada");
                    return;
                }
                if(e.equals(salidaMboton)){
                    panelContenedor.setSelectedIndex(1);
                    labelMenuActual.setText("Salida");
                    return;
                }
                if(e.equals(stockBoton)){
                    panelContenedor.setSelectedIndex(2);
                    labelMenuActual.setText("Stock");
                    return;
                }
                if(e.equals(proveedoresBoton)){
                    panelContenedor.setSelectedIndex(3);
                    labelMenuActual.setText("Proveedores");
                    return;
                }
                if(e.equals(personalBoton)){
                    panelContenedor.setSelectedIndex(4);
                    labelMenuActual.setText("Personal");
                    return;
                }
                if(e.equals(cotizacionBoton)){
                    panelContenedor.setSelectedIndex(5);
                    labelMenuActual.setText("Cotizacion");
                    return;
                }
                if(e.equals(seguimientoBoton)){
                    panelContenedor.setSelectedIndex(6);
                    labelMenuActual.setText("Seguimiento");
                    return;
                }
            }
        };
        
        entradaMBoton.addMouseListener(maBotonesMenu);
        salidaMboton.addMouseListener(maBotonesMenu);
        stockBoton.addMouseListener(maBotonesMenu);
        proveedoresBoton.addMouseListener(maBotonesMenu);
        personalBoton.addMouseListener(maBotonesMenu);
        cotizacionBoton.addMouseListener(maBotonesMenu);
        seguimientoBoton.addMouseListener(maBotonesMenu);
        
        scrollPanelMenu.setVerticalScrollBar(new ScrollBarCustom());
        scrollPanelMenu.getVerticalScrollBar().setUnitIncrement(30);
        
        labelFecha.setText(formatter.format(date));
        labelMenuActual.setText("Bienvenido");
        panelContenedor.setSelectedIndex(7);
        //</editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Menu Entradas Code">              
        JTableHeader headerEntradas = tablaEntradas.getTableHeader();
        headerEntradas.setDefaultRenderer(new CustomHeader());
        tablaEntradas.setTableHeader(headerEntradas);
        
        tablaEntradas.getTableHeader().setBackground(new Color(64,110,36));
        tablaEntradas.getTableHeader().setFont(new Font("Corbel", 1, 1));
        String[] titulos = {"Numero","Piezas","Codigo","Nombre","Estado","Proveedor","Fecha"};
        Object[][] datos = new Object[0][0];
        modeloTablaEntrada = new ModeloTabla(datos,titulos, true);
        tablaEntradas.setModel(modeloTablaEntrada);
        scrollEntradas.setVerticalScrollBar(new ScrollBarCustom());
        scrollEntradas.getVerticalScrollBar().setUnitIncrement(30);
        //</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc="Menu Salidas Code">
        

        JTableHeader headerSalidas = tablaSalida.getTableHeader();
	headerSalidas.setDefaultRenderer(new CustomHeader());
	tablaSalida.setTableHeader(headerSalidas);
        String[] titulosSalida = {"Numero","Piezas","Codigo","Nombre","Personal","Lugar","Estado","Fecha"};
        Object[][] datosSalida = new Object[0][0];
        modeloTablaSalida = new ModeloTabla(datosSalida,titulosSalida, true);           
        tablaSalida.getTableHeader().setBackground(new Color(64,110,36));
        tablaSalida.getTableHeader().setFont(new Font("Corbel", 1, 1));
        tablaSalida.setModel(modeloTablaSalida);
        //</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc="Menu Stock Code">
        JTableHeader headerStock = tablaStock.getTableHeader();
	headerStock.setDefaultRenderer(new CustomHeader());
	tablaStock.setTableHeader(headerStock);
        String[] titulosStock = {"Numero","Piezas","Codigo","Nombre","Modelo","Proveedor","Estado","Observacion","Fecha"};
        Object[][] datosStock = new Object[1][0];
        modeloTablaStock = new ModeloTabla(datosStock,titulosStock, true);           
        tablaStock.getTableHeader().setBackground(new Color(64,110,36));
        tablaStock.getTableHeader().setFont(new Font("Corbel", 1, 1));
        tablaStock.setModel(modeloTablaStock);
        scrollStock.setVerticalScrollBar(new ScrollBarCustom());
        scrollStock.getVerticalScrollBar().setUnitIncrement(30);
        //</editor-fold>
        }
    private void llevarAMenu(int index){
        panelContenedor.setSelectedIndex(index);
    }
    private void ponerImagen(JLabel lb, String ruta){
       ImageIcon imagen = new ImageIcon(ruta);
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_SMOOTH));
       lb.setIcon(icono);
       this.repaint();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
//<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajustesboton;
    private javax.swing.JLabel articulosBoton;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JButton botonAñadirEntrada;
    private javax.swing.JButton botonAñadirSalida;
    private javax.swing.JLabel botonCerrar;
    private javax.swing.JButton botonEliminarEntrada;
    private javax.swing.JButton botonEliminarSalida;
    private javax.swing.JButton botonGuardarEntrada;
    private javax.swing.JButton botonGuardarSalida;
    private javax.swing.JLabel botonMinimizar;
    private javax.swing.JLabel cierreMBoton;
    private javax.swing.JLabel cotizacionBoton;
    private javax.swing.JLabel entradaMBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel labelCotizacion;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelMenuActual;
    private javax.swing.JLabel labelPersonal;
    private javax.swing.JLabel labelProveedores;
    private javax.swing.JLabel labelSeguimiento;
    private javax.swing.JLabel logoITS;
    private javax.swing.JLabel observacionesBoton;
    private javax.swing.JLabel ordenBoton;
    private javax.swing.JTabbedPane panelContenedor;
    private javax.swing.JPanel panelCotizacion;
    private javax.swing.JPanel panelEntrada;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMenuPrincipal;
    private javax.swing.JPanel panelPersonal;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JPanel panelSalida;
    private javax.swing.JPanel panelSeguimiento;
    private javax.swing.JPanel panelStock;
    private javax.swing.JLabel personalBoton;
    private javax.swing.JLabel proveedoresBoton;
    private javax.swing.JLabel salidaMboton;
    private javax.swing.JScrollPane scrollEntradas;
    private javax.swing.JScrollPane scrollPanelMenu;
    private javax.swing.JScrollPane scrollSalida;
    private javax.swing.JScrollPane scrollStock;
    private javax.swing.JLabel seguimientoBoton;
    private javax.swing.JLabel stockBoton;
    private javax.swing.JTable tablaEntradas;
    private javax.swing.JTable tablaSalida;
    private javax.swing.JTable tablaStock;
    private javax.swing.JLabel textoInstitucion;
    // End of variables declaration//GEN-END:variables
    private MouseAdapter maBotonesMenu;
    private int xMouse;
    private int yMouse;
    DefaultTableModel modeloTablaEntrada;
    Date date = new Date();
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yy"); 
    DefaultTableModel modeloTablaSalida;
    DefaultTableModel modeloTablaStock;
    JLabel[] botonesMenu = {entradaMBoton, salidaMboton, stockBoton, proveedoresBoton, personalBoton, cotizacionBoton, seguimientoBoton};
    //</editor-fold>
      
   
    //</editor-fold>
}
