USE ALMACEN;

CREATE TABLE DESTINO (
  idDESTINO INTEGER   NOT NULL ,
  NOMBRE VARCHAR (50)     ,
PRIMARY KEY(idDESTINO));




CREATE TABLE REQUISICIONES (
  idREQUISICIONES INTEGER   NOT NULL ,
  NUM_REQ NUMERIC(20), 
  JEF VARCHAR    ,
  PLANE VARCHAR    ,
  SUB VARCHAR    ,
  DIR VARCHAR    ,
  COM VARCHAR    ,
  REC VARCHAR    ,
  OBSERV VARCHAR(40)    ,
  FECHA DATE      ,
PRIMARY KEY(idREQUISICIONES));




CREATE TABLE COTIZACION (
  idCOTIZACION INTEGER   NOT NULL ,
  ARTIC VARCHAR(30)    ,
  UM VARCHAR(10)    ,
  CANT INTEGER    ,
  CLAVE INTEGER    ,
  FERR CHAR    ,
  ELECT CHAR    ,
  PLOM CHAR      ,
PRIMARY KEY(idCOTIZACION));




CREATE TABLE AREAS (
  IDAREAS INTEGER   NOT NULL ,
  NOMBRE VARCHAR(30)      ,
PRIMARY KEY(IDAREAS));




CREATE TABLE STOCK (
  idSTOCK INTEGER   NOT NULL ,
  IDAREAS INTEGER   NOT NULL ,
  PZAS INTEGER    ,
  CODIGO INTEGER    ,
  NOM_ART VARCHAR(30)    ,
  MARCA VARCHAR(20)    ,
  MINIMO INTEGER      ,
PRIMARY KEY(idSTOCK));




CREATE TABLE CIERRE_MATERIAL (
  idCIERRE_MATERIAL INTEGER   NOT NULL ,
  idREQUISICIONES INTEGER   NOT NULL ,
  OC INTEGER    ,
  NUM_FAC INTEGER    ,
  PROVEEDOR VARCHAR(30)    ,
  FEC_SOL DATE    ,
  FEC_ENT DATE    ,
  NOMBRE VARCHAR(30)    ,
  OBSERV VARCHAR(30)      ,
PRIMARY KEY(idCIERRE_MATERIAL));




CREATE TABLE ENTRADA (
  idENTRADA INTEGER   NOT NULL ,
  idCIERRE_MATERIAL INTEGER   NOT NULL ,
  idSTOCK INTEGER   NOT NULL ,
  UNIDADES INTEGER    ,
  ESTADO VARCHAR(20)    ,
  FECHA DATE      ,
PRIMARY KEY(idENTRADA));




CREATE TABLE SALIDA (
  idSALIDA INTEGER   NOT NULL ,
  idDESTINO INTEGER   NOT NULL ,
  idSTOCK INTEGER   NOT NULL ,
  PZAS INTEGER    ,
  PERSONAL VARCHAR(30)    ,
  OBSERV VARCHAR(20)    ,
  FECHA DATE      ,
PRIMARY KEY(idSALIDA));


ALTER TABLE CIERRE_MATERIAL
ADD CONSTRAINT FK_IDREQUISICIONES FOREIGN KEY (IDREQUISICIONES)
REFERENCES REQUISICIONES (IDREQUISICIONES);

ALTER TABLE ENTRADA
ADD CONSTRAINT FK_ID_CIERRE FOREIGN KEY (IDCIERRE_MATERIAL)
REFERENCES CIERRE_MATERIAL (IDCIERRE_MATERIAL);

ALTER TABLE ENTRADA
ADD CONSTRAINT FK_ID_STOCK FOREIGN KEY (IDSTOCK)
REFERENCES STOCK (IDSTOCK);

ALTER TABLE STOCK
ADD CONSTRAINT FK_ID_AREAS FOREIGN KEY (IDAREAS)
REFERENCES AREAS (IDAREAS);

ALTER TABLE SALIDA
ADD CONSTRAINT FK_ID_STOCK_S FOREIGN KEY (IDSTOCK)
REFERENCES STOCK (IDSTOCK);

ALTER TABLE SALIDA
ADD CONSTRAINT FK_ID_DESTINO FOREIGN KEY (IDDESTINO)
REFERENCES DESTINO (IDDESTINO);